name: Ansible Deployment

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]

jobs:
  run-ansible:
    runs_on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v4

      - name: listout
        run: |
          pwd
          ls -ltr
          ansible --version
          echo "${{secrets.EC2_SSH_PRIVATE_KEY}}" > /tmp/key.pem
          chmod 400 /tmp/key.pem
      - name: Run Playbook
        run:
          ansible-playbook -i inventories/dev.ini playbook.yml   